{"name": "При попытке повторной регистрации, в ответе возвращается ошибка 403: \"User already exists\"", "status": "passed", "start": 1706194580979, "stop": 1706194581122, "uuid": "7d08c800-9b6a-44e6-8c1d-02f745bc12a4", "historyId": "e38d5458ce2aefe70054cddd7f71966d", "testCaseId": "e38d5458ce2aefe70054cddd7f71966d", "fullName": "tests.test_create_user.TestCreateUser#test__create_user__duplicate_user__user_already_exists", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Lenovo-1"}, {"name": "thread", "value": "6100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}